// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: relay.proto

package relaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayControl_StartRun_FullMethodName  = "/relay.v1.RelayControl/StartRun"
	RelayControl_GetStatus_FullMethodName = "/relay.v1.RelayControl/GetStatus"
	RelayControl_Approve_FullMethodName   = "/relay.v1.RelayControl/Approve"
)

// RelayControlClient is the client API for RelayControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Control plane for durable agent pipelines. The Python server proxies
// these calls to Temporal (start / query / signal).
type RelayControlClient interface {
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunReply, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
	Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveReply, error)
}

type relayControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayControlClient(cc grpc.ClientConnInterface) RelayControlClient {
	return &relayControlClient{cc}
}

func (c *relayControlClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRunReply)
	err := c.cc.Invoke(ctx, RelayControl_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, RelayControl_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayControlClient) Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveReply)
	err := c.cc.Invoke(ctx, RelayControl_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayControlServer is the server API for RelayControl service.
// All implementations must embed UnimplementedRelayControlServer
// for forward compatibility.
//
// Control plane for durable agent pipelines. The Python server proxies
// these calls to Temporal (start / query / signal).
type RelayControlServer interface {
	StartRun(context.Context, *StartRunRequest) (*StartRunReply, error)
	GetStatus(context.Context, *StatusRequest) (*StatusReply, error)
	Approve(context.Context, *ApproveRequest) (*ApproveReply, error)
	mustEmbedUnimplementedRelayControlServer()
}

// UnimplementedRelayControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayControlServer struct{}

func (UnimplementedRelayControlServer) StartRun(context.Context, *StartRunRequest) (*StartRunReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedRelayControlServer) GetStatus(context.Context, *StatusRequest) (*StatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRelayControlServer) Approve(context.Context, *ApproveRequest) (*ApproveReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedRelayControlServer) mustEmbedUnimplementedRelayControlServer() {}
func (UnimplementedRelayControlServer) testEmbeddedByValue()                      {}

// UnsafeRelayControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayControlServer will
// result in compilation errors.
type UnsafeRelayControlServer interface {
	mustEmbedUnimplementedRelayControlServer()
}

func RegisterRelayControlServer(s grpc.ServiceRegistrar, srv RelayControlServer) {
	// If the following call panics, it indicates UnimplementedRelayControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayControl_ServiceDesc, srv)
}

func _RelayControl_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayControl_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayControlServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayControl_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayControlServer).Approve(ctx, req.(*ApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayControl_ServiceDesc is the grpc.ServiceDesc for RelayControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relay.v1.RelayControl",
	HandlerType: (*RelayControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _RelayControl_StartRun_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _RelayControl_GetStatus_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _RelayControl_Approve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relay.proto",
}
