# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from relay.relaypb import relay_pb2 as relay__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in relay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RelayControlStub:
    """Control plane for durable agent pipelines. The Python server proxies
    these calls to Temporal (start / query / signal).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRun = channel.unary_unary(
                '/relay.v1.RelayControl/StartRun',
                request_serializer=relay__pb2.StartRunRequest.SerializeToString,
                response_deserializer=relay__pb2.StartRunReply.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/relay.v1.RelayControl/GetStatus',
                request_serializer=relay__pb2.StatusRequest.SerializeToString,
                response_deserializer=relay__pb2.StatusReply.FromString,
                _registered_method=True)
        self.Approve = channel.unary_unary(
                '/relay.v1.RelayControl/Approve',
                request_serializer=relay__pb2.ApproveRequest.SerializeToString,
                response_deserializer=relay__pb2.ApproveReply.FromString,
                _registered_method=True)


class RelayControlServicer:
    """Control plane for durable agent pipelines. The Python server proxies
    these calls to Temporal (start / query / signal).
    """

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Approve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=relay__pb2.StartRunRequest.FromString,
                    response_serializer=relay__pb2.StartRunReply.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=relay__pb2.StatusRequest.FromString,
                    response_serializer=relay__pb2.StatusReply.SerializeToString,
            ),
            'Approve': grpc.unary_unary_rpc_method_handler(
                    servicer.Approve,
                    request_deserializer=relay__pb2.ApproveRequest.FromString,
                    response_serializer=relay__pb2.ApproveReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relay.v1.RelayControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('relay.v1.RelayControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelayControl:
    """Control plane for durable agent pipelines. The Python server proxies
    these calls to Temporal (start / query / signal).
    """

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relay.v1.RelayControl/StartRun',
            relay__pb2.StartRunRequest.SerializeToString,
            relay__pb2.StartRunReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relay.v1.RelayControl/GetStatus',
            relay__pb2.StatusRequest.SerializeToString,
            relay__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Approve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relay.v1.RelayControl/Approve',
            relay__pb2.ApproveRequest.SerializeToString,
            relay__pb2.ApproveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
