# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relay.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'relay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brelay.proto\x12\x08relay.v1\"9\n\x0fStartRunRequest\x12\x0c\n\x04task\x18\x01 \x01(\t\x12\x18\n\x10require_approval\x18\x02 \x01(\x08\"$\n\rStartRunReply\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\"$\n\rStatusRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"5\n\x0e\x41pproveRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x0e\n\x06reject\x18\x02 \x01(\x08\"\x1e\n\x0c\x41pproveReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc8\x01\n\x0cRelayControl\x12>\n\x08StartRun\x12\x19.relay.v1.StartRunRequest\x1a\x17.relay.v1.StartRunReply\x12;\n\tGetStatus\x12\x17.relay.v1.StatusRequest\x1a\x15.relay.v1.StatusReply\x12;\n\x07\x41pprove\x12\x18.relay.v1.ApproveRequest\x1a\x16.relay.v1.ApproveReplyB/Z-github.com/adarsh-sgh/relay/go-client/relaypbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/adarsh-sgh/relay/go-client/relaypb'
  _globals['_STARTRUNREQUEST']._serialized_start=25
  _globals['_STARTRUNREQUEST']._serialized_end=82
  _globals['_STARTRUNREPLY']._serialized_start=84
  _globals['_STARTRUNREPLY']._serialized_end=120
  _globals['_STATUSREQUEST']._serialized_start=122
  _globals['_STATUSREQUEST']._serialized_end=158
  _globals['_STATUSREPLY']._serialized_start=160
  _globals['_STATUSREPLY']._serialized_end=189
  _globals['_APPROVEREQUEST']._serialized_start=191
  _globals['_APPROVEREQUEST']._serialized_end=244
  _globals['_APPROVEREPLY']._serialized_start=246
  _globals['_APPROVEREPLY']._serialized_end=276
  _globals['_RELAYCONTROL']._serialized_start=279
  _globals['_RELAYCONTROL']._serialized_end=479
# @@protoc_insertion_point(module_scope)
